### ISSUE TITLE
Control + middle clicking

### ISSUE THREAD

**Issue by SuperBlim** [GeheimagentNr1/BridgeMaker#3]
### Minecraft Version

1.20.6

### Minecraft Forge Version

50.0.31

### Mod Version

1.20.6

### Describe the bug

place the bridge block and crtl middle click

### Expected behavior

i was suposed to copy the inventory of the item into nbt data like with chests

### Steps to reproduce

1. place the bridge block
2. hold control and middle click the block

### References (optional)

none

### Additional info (optional)

worked multiple times

**Comment by GeheimagentNr1** [comment]
<table>
    <tbody>
        <tr>
            <th>
                Status:
            </th>    
            <td>
                Fixed
            </td>
        </tr>
        <tr>
            <th>
                Issue type:
            </th>
            <td>
                Bug
            </td>
        </tr>
        <tr>
            <th>
                Fix type:
            </th>
            <td>
                Bugfix
            </td>
        </tr>
        <tr>
            <th>
                Fix version:
            </th>
            <td>
                2.0.4
            </td>
        </tr>
        <tr>
            <th>
                Fix release date:
            </th>
            <td>
                14.06.24
            </td>
        </tr>
    </tbody>
</table>

**Issue confirmed for:**

*   Minecraft version: 1.20.6
     Forge version: 50.0.28
     Mod version: 2.0.4

**TODOs:**

*   [x] Check issue and search a fix

**Comment by GeheimagentNr1** [comment]
The issue has been fixed with version 2.0.4 and has just been uploaded.
